(include_subdirs (unqualified))

(library
 (public_name jsonkit.ppx)
 (name ppx_deriving_json_native)
 (modules :standard \ ppx_deriving_json_native_test)
 (libraries ppxlib)
 (ppx_runtime_libraries jsonkit yojson)
 (preprocess
  (pps ppxlib.metaquot))
 (kind ppx_deriver))

(executable
 (name ppx_deriving_json_native_test)
 (modules ppx_deriving_json_native_test)
 (libraries jsonkit.ppx ppxlib))

(rule
 (target ppx_deriving_json_native.mli)
 (action
  (with-stdout-to
   %{target}
   (run echo ""))))

(rule
 (target ppx_deriving_json_native_test.ml)
 (action
  (with-stdout-to
   %{target}
   (run echo "let () = Ppxlib.Driver.standalone ()"))))

(copy_files#
 (files ../jsonschema/{schema,ppx_deriving_jsonschema}.{ml,mli}))

